### ISSUE TITLE
can support mod server?

### ISSUE THREAD

**Issue by EthanO3O** [DRE2N/HolographicMenus#4]
My server side is Thermos 1710-1614.46
The plugin do not work on it ：(
But it looked so cool

**Comment by Sataniel98** [comment]
"Doesn't work" doesn't help. What exactly doesn't work?

**Comment by EthanO3O** [comment]
I mean I put it in plugins and start server
and then,the plugin did not load
there is no config folder

**Comment by Sataniel98** [comment]
I need at least an error stacktrace.

**Comment by EthanO3O** [comment]
yeah you are right 
[23:53:56] [Server thread/ERROR]: Could not load 'plugins\HolographicMenus-v1.0-1.7.9.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: HolographicDisplays
    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:223) [SimplePluginManager.class:1.7.10-1614.46]
    at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugins(CraftServer.java:320) [CraftServer.class:1.7.10-1614.46]
    at net.minecraft.world.storage.SaveHandler.initBukkitData(SaveHandler.java:461) [ayq.class:?]
    at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:137) [ayq.class:?]
    at net.minecraft.world.World.<init>(World.java:365) [ahb.class:?]
    at net.minecraft.world.WorldServer.<init>(WorldServer.java:162) [mt.class:?]
    at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:369) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:336) [lt.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:633) [MinecraftServer.class:?]
    at java.lang.Thread.run(Unknown Source) 

any help?

**Comment by Sataniel98** [comment]
You don't have HolographicDisplays and ProtocolLib installed, do you?

**Comment by EthanO3O** [comment]
ah  
I don't have HolographicDisplays
only have  ProtocolLib

**Comment by EthanO3O** [comment]
Thanks a lot
I installed the HolographicDisplays and it worked :3

**Comment by Sataniel98** [comment]
No problem, you'll also need ProtocolLib if you don't want everyone to see each others menus.
